{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.1.jar",
          "url": "gradle-plugin-1.1.jar",
          "size": 10459,
          "sha512": "f7eb4d2f5725f2becd0e0bbc2ffa7396334f92027dc40eeb3f908f8f2aa6ce787c917cbd2d2f25acd921671b295e22b0143918981784513953e3b0fba4e3c2f6",
          "sha256": "ee7b7093a7a703ced77458ceeacd52c5c80289dbb56e7efa9b1d53580d1c173e",
          "sha1": "1ed76c485101e27369125133aa4650b6a649ddf5",
          "md5": "b447549a510ed571c4bebfc0ef839fcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.1.jar",
          "url": "gradle-plugin-1.1.jar",
          "size": 10459,
          "sha512": "f7eb4d2f5725f2becd0e0bbc2ffa7396334f92027dc40eeb3f908f8f2aa6ce787c917cbd2d2f25acd921671b295e22b0143918981784513953e3b0fba4e3c2f6",
          "sha256": "ee7b7093a7a703ced77458ceeacd52c5c80289dbb56e7efa9b1d53580d1c173e",
          "sha1": "1ed76c485101e27369125133aa4650b6a649ddf5",
          "md5": "b447549a510ed571c4bebfc0ef839fcc"
        }
      ]
    }
  ]
}
