{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.jar",
          "url": "gradle-plugin-1.2.jar",
          "size": 10765,
          "sha512": "fa4d57e81f44a4f2542ac651950372c475e3e3b108d8c1188bdeddf9003328893510dbffc71e8cd7a936cc5410ab1d054f554a4657769da6c2f132aa60676615",
          "sha256": "f0cbc21b2934306e4dc149c62f89e5854648858b7baa40b273ae4f638416235c",
          "sha1": "20be37d388010f5ae72dd028c7b9c8a44c63da61",
          "md5": "0d23ebeba133add3a75f49cda25130b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.jar",
          "url": "gradle-plugin-1.2.jar",
          "size": 10765,
          "sha512": "fa4d57e81f44a4f2542ac651950372c475e3e3b108d8c1188bdeddf9003328893510dbffc71e8cd7a936cc5410ab1d054f554a4657769da6c2f132aa60676615",
          "sha256": "f0cbc21b2934306e4dc149c62f89e5854648858b7baa40b273ae4f638416235c",
          "sha1": "20be37d388010f5ae72dd028c7b9c8a44c63da61",
          "md5": "0d23ebeba133add3a75f49cda25130b9"
        }
      ]
    }
  ]
}
