{
  "formatVersion": "1.1",
  "component": {
    "group": "com.minthuya.gradle.plugin",
    "module": "gradle-plugin",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.jar",
          "url": "gradle-plugin-1.2.jar",
          "size": 10765,
          "sha512": "c0b1e6cc289c807142707f0896ddbbcf019806a6de48923646cc6056fc21751d03413f861eeb72074b79c90d77ed3a0215954224a73cd4f1896d7d4bce18e7b2",
          "sha256": "43e511ec6357c36899f901c9de00737dd1bdad9382cc586b35c87b03d3daf351",
          "sha1": "d075f9bcd164945636e042b87c51303433df8ccd",
          "md5": "23413e3974629deaf898ae79f901a51f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-1.2.jar",
          "url": "gradle-plugin-1.2.jar",
          "size": 10765,
          "sha512": "c0b1e6cc289c807142707f0896ddbbcf019806a6de48923646cc6056fc21751d03413f861eeb72074b79c90d77ed3a0215954224a73cd4f1896d7d4bce18e7b2",
          "sha256": "43e511ec6357c36899f901c9de00737dd1bdad9382cc586b35c87b03d3daf351",
          "sha1": "d075f9bcd164945636e042b87c51303433df8ccd",
          "md5": "23413e3974629deaf898ae79f901a51f"
        }
      ]
    }
  ]
}
